apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-db-gateway
spec:
{{- if .Values.numGatewayPods }}
  replicas: {{ .Values.numGatewayPods }}
{{- end }}
  selector:
    matchLabels:
      run: movies-db-gateway
  template:
    metadata:
      labels:
        run: movies-db-gateway
    spec:
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
{{- end }}
      containers:
        - name: movies-db-gateway
          image: {{if .Values.registry }}{{ .Values.registry }}/{{ end }}srserver01/movies-db-gateway
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: movies-db-gateway
  labels:
    run: movies-db-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: {{ .Values.entryNodePort }}
  selector:
    run: movies-db-gateway
