FROM docker.io/alpine:3.18.2

RUN apk update && apk upgrade && apk add --no-cache bash gawk sed grep bc coreutils curl file

ADD movies-db-service/target/release/movies-db-cli /opt/movies-db/bin/movies-db-cli
ADD docker/start_movie_service.sh /opt/movies-db/bin/start_movie_service.sh

RUN chown -R root:root /opt/movies-db
RUN chmod +x /opt/movies-db/bin/movies-db-cli
RUN chmod +x /opt/movies-db/bin/start_movie_service.sh

EXPOSE 3030

CMD [ "sleep", "1000000" ]

# ENTRYPOINT [ "/opt/movies-db/bin/start_movie_service.sh" ]
