kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: movies-db-storage-pvc
  labels:
    app: movies-db-service
spec:
  selector:
    matchLabels:
      app: movies-db-service
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-db-service
spec:
  selector:
    matchLabels:
      run: movies-db-service
  replicas: 1
  template:
    metadata:
      labels:
        run: movies-db-service
    spec:
      containers:
        - name: movies-db-service
          image: srserver01/movies-db-service
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "trace"
          ports:
            - containerPort: 3030
          volumeMounts:
            - mountPath: /var/data/movies
              name: movies-db-storage
      volumes:
        - name: movies-db-storage
          persistentVolumeClaim:
            claimName: movies-db-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: movies-db-service
  labels:
    run: movies-db-service
spec:
  ports:
    - port: 3030
      protocol: TCP
  selector:
    run: movies-db-service
