apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-db-gateway
spec:
  selector:
    matchLabels:
      run: movies-db-gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: movies-db-gateway
    spec:
      containers:
        - name: movies-db-gateway
          image: srserver01/movies-db-gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: movies-db-gateway
  labels:
    run: movies-db-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30087
  selector:
    run: movies-db-gateway
