# Provide the registry for pulling the images. By default the docker hub registry is being used.
registry: ghcr.io

# The tag for the images. By default the latest tag is being used.
tag: 0.1.0

imagePullPolicy: Always

# Use a DockerPullSecret
imagePullSecret:

# The externally exposed (Node-)port.
entryNodePort: 30042

# The configuration of the backend service
backend:
  # The storage size for the movies
  storage: 100Gi

  # Optionally, specify the storage class to use
  # storageClass:

  # The access mode of the storage. As currently, only one replica is being used,
  # ReadWriteOnce is sufficient.
  accessMode: ReadWriteMany

  # The log level for the backend service
  log_level: info

# Set the number of pods to be deployed for delivering the UI application.
numUIPods: 1

# Set the number of gateway pods to be deployed for delivering overall API.
numGatewayPods: 1

# Set the number of pods to be deployed for movies-db backend service.
numBackendPods: 1
